<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-14E9C6J" failures="1" tests="6" name="regressionTest" time="80.859" errors="0" timestamp="2025-05-26T21:21:06 IST">
  <testcase classname="com.sevenmartsupermarket.tests.HomeTest" name="verifyAdminMoreInfoButton" time="3.234"/>
  <testcase classname="com.sevenmartsupermarket.tests.HomeTest" name="verifyManageNewsMoreInfo" time="5.428"/>
  <testcase classname="com.sevenmartsupermarket.tests.HomeTest" name="verifyRetryFailure" time="1.317">
    <skipped/>
  </testcase> <!-- verifyRetryFailure -->
  <testcase classname="com.sevenmartsupermarket.tests.HomeTest" name="verifyRetryFailure" time="6.516">
    <skipped/>
  </testcase> <!-- verifyRetryFailure -->
  <testcase classname="com.sevenmartsupermarket.tests.HomeTest" name="verifyRetryFailure" time="2.121">
    <skipped/>
  </testcase> <!-- verifyRetryFailure -->
  <testcase classname="com.sevenmartsupermarket.tests.HomeTest" name="verifyRetryFailure" time="5.211">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.sevenmartsupermarket.tests.HomeTest.verifyRetryFailure(HomeTest.java:39)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- verifyRetryFailure -->
</testsuite> <!-- regressionTest -->
